# PyTorch Learn

- [learn from video series](https://www.youtube.com/watch?v=Csa5R12jYRg&list=PLZbbT5o_s2xrfNyHZsM6ufI0iZENK9xgG&index=5)

 ## Verifying the installation

In [14]:
import torch 

In [15]:
print(torch.__version__)

1.2.0


In [16]:
torch.cuda.is_available()

True

In [17]:
torch.version.cuda

'10.0'

## Using CUDA

- GPU is good at parallel computation.

In [18]:
t = torch.tensor([1,2,3])
t

tensor([1, 2, 3])

In [20]:
t = t.cuda()
t

tensor([1, 2, 3], device='cuda:0')

## Tensor

- tensor是数学上的说法,在计算机领域tensor即为n维数组(nd-array)
- 标量是零维tensor，向量是一维tensor，矩阵是二维tensor

### Rank

- rank是一个张量的维数 如一个矩阵是一个rank-2张量
- rank表示需要多少下标(indices)来得到一个数据
- rank标明了axes的数量

### Axis

- 张量的某个维度(a specific dimension of a tensor)
- 若一个张量是二位张量，则它有两个Axis(Axes)
- 每一个axis的长度表示在这一个axis中有效的下标(indices)数量

### Shape

- 是由张量每一个axis的长度决定的

In [22]:
dd = [[1,2,3],[4,5,6],[7,8,9]]
t = torch.tensor(dd)
t

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [23]:
type(t)

torch.Tensor

In [24]:
t.shape

torch.Size([3, 3])

- 上面的张量t的每一个axis长度为3
- shape的长度等于张量的rank
- 要注意，**shape每一个分量的乘积必须等于数据的个数**

In [25]:
len(t.shape)

2

#### Reshape

**Shape $6 \times 1$**

- number
- scalar
- array
- vector
- 2d-array
- matrix

**Shape $2 \times 3$**

- number,array,2d-array
- scalar,vector,matrix

**Shape $3 \times 2$**

- number,scalar
- array,vector
- 2d-array,matrix

- reshaping只是改变数据的分组，而不改变数据

In [26]:
t_reshape = t.reshape(1,9)
t_reshape

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [27]:
t_reshape.shape

torch.Size([1, 9])

### Take input tensor of CNN as an example

- 通常CNN的输入张量的rank为4
- 最后两个axes分别是图像的Height和width
- 第二个axis是color channel，即RGB
- 第一个axis是batch的大小，即里面含多少个samples

### PyTorch Tensor

In [1]:
import numpy as np
import torch

#### Tensor Class

- Tensors in PyTorch are represented using the ``torch.Tensor`` class

In [2]:
t = torch.Tensor()
type(t)

torch.Tensor

#### Tensor Attributes

In [5]:
print(t.dtype)
print(t.device)
print(t.layout)
print(torch.device('cuda:0')) #指定下标为0的GPU

torch.float32
cpu
torch.strided
cuda:0


- 张量之间的运算 张量的``dtype``必须相同
- 两个张量的运算 必须在同一个device上

#### Create tensors options

In [6]:
data = np.array([1,2,3])
type(data)

numpy.ndarray

In [7]:
torch.Tensor(data) # 注意tensor是float类型

tensor([1., 2., 3.])

In [8]:
torch.tensor(data) # 注意tensor是int类型

tensor([1, 2, 3], dtype=torch.int32)

In [9]:
torch.as_tensor(data)

tensor([1, 2, 3], dtype=torch.int32)

In [10]:
torch.from_numpy(data)

tensor([1, 2, 3], dtype=torch.int32)

#### Best Options to Create Tensor

In [11]:
t1 = torch.Tensor(data) # .Tensor is a class constructor
t2 = torch.tensor(data) # .tensor is a factory function input a param return an object
t3 = torch.as_tensor(data)# .as_tensor is a factory function
t4 = torch.from_numpy(data)# same as above

In [12]:
print(t1.dtype)
print(t2.dtype)
print(t3.dtype)
print(t4.dtype)

torch.float32
torch.int32
torch.int32
torch.int32


In [13]:
torch.get_default_dtype()

torch.float32

- 后三个factory function返回与输入的data同类型的tensor 这个叫做**type inference**
- ``dtype``可以设定

In [14]:
torch.tensor(np.array([1,2,3]),dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

- 如果更改data的值(而非tensor的值)，上面的四个选项会有不同的结果

In [15]:
data[0] = 0
data[1] = 0
data[2] = 0

In [16]:
print(t1)
print(t2)
print(t3)
print(t4)

tensor([1., 2., 3.])
tensor([1, 2, 3], dtype=torch.int32)
tensor([0, 0, 0], dtype=torch.int32)
tensor([0, 0, 0], dtype=torch.int32)


- 前两个 在tensor中保存了最原始的data的值，修改data不会影响张量 **copy memory of the data**
- 后两个 保存了“现在”data的数据 **share memory of the data**
- Best option is ``torch.tensor()``
- 如果想要节约内存，提高性能 ``torch.as_tensor()``
    - 注意事项
    - ``numpy.ndarray``是分配在CPU上的，如果要用GPU，``as_tensor()``必须将数据从CPU复制 到GPU
    - ``as_tensor()``does not work with **built-in Python data structures like lists**
- ``torch.as_tensor()``可以接受任何形式的array
- ``torch.from_numpy()``只能接受numpy array

### Tensor Operations

1. Reshaping
2. Element-wise
3. Redution
4. Access

#### Reshaping

In [17]:
import torch

In [18]:
t = torch.tensor([
    [1,1,1,1],
    [2,2,2,2],
    [3,3,3,3]
],dtype = torch.float32)

In [21]:
t.size() # get shape

torch.Size([3, 4])

In [22]:
t.shape # get shape

torch.Size([3, 4])

In [23]:
len(t.shape) # get rank

2

In [24]:
torch.tensor(t.shape).prod() # get elements number

tensor(12)

In [25]:
t.numel() # get elements number

12

In [26]:
t.reshape(1,12)

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])

In [27]:
t.reshape(2,6)

tensor([[1., 1., 1., 1., 2., 2.],
        [2., 2., 3., 3., 3., 3.]])

In [28]:
t.reshape(4,3)

tensor([[1., 1., 1.],
        [1., 2., 2.],
        [2., 2., 3.],
        [3., 3., 3.]])

##### Squeezing Unsqueezing

- Squeezing操作将tensor变为1d
- Unsqueezing操作将tensor的rank加一

In [29]:
print(t.reshape(1,12))
print(t.reshape(1,12).shape)

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])
torch.Size([1, 12])


In [30]:
print(t.reshape(1,12).squeeze())
print(t.reshape(1,12).squeeze().shape)

tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.])
torch.Size([12])


In [31]:
print(t.reshape(1,12).squeeze().unsqueeze(dim=0))
print(t.reshape(1,12).squeeze().unsqueeze(dim=0).shape)

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])
torch.Size([1, 12])


##### Flatten

- 是reshape和squeeze的结合
- CNN中convolutional layer传递给fully connected layer的张量 must be flatten out

In [32]:
def flatten(t):
    t = t.reshape(1,-1) # -1是获得一个tensor中数据的数量
    t = t.squeeze()
    return t

In [33]:
flatten(t)

tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.])

##### Concatenating

In [34]:
t1 = torch.tensor([
    [1,2],
    [3,4]
])

In [35]:
t2 = torch.tensor([
    [5,6],
    [7,8]
])

In [36]:
torch.cat((t1,t2),dim=0) # first axis cat

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])

In [37]:
torch.cat((t1,t2),dim=1) # second axis cat

tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])

##### CNN Flatten Operation——Tensor Batch Processing

In [38]:
import torch

In [43]:
t1 = torch.tensor([
    [1,1,1,1],
    [1,1,1,1],
    [1,1,1,1],
    [1,1,1,1]
])

t2 = torch.tensor([
    [2,2,2,2],
    [2,2,2,2],
    [2,2,2,2],
    [2,2,2,2]
])

t3 = torch.tensor([
    [3,3,3,3],
    [3,3,3,3],
    [3,3,3,3],
    [3,3,3,3]
])

t4 = torch.tensor([
    [4,4,4,4],
    [4,4,4,4],
    [4,4,4,4],
    [4,4,4,4]
])

In [44]:
t = torch.stack((t1,t2,t3))

In [45]:
t.shape

torch.Size([3, 4, 4])

In [46]:
t

tensor([[[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]],

        [[2, 2, 2, 2],
         [2, 2, 2, 2],
         [2, 2, 2, 2],
         [2, 2, 2, 2]],

        [[3, 3, 3, 3],
         [3, 3, 3, 3],
         [3, 3, 3, 3],
         [3, 3, 3, 3]]])

In [47]:
t = t.reshape(3,1,4,4)
t

tensor([[[[1, 1, 1, 1],
          [1, 1, 1, 1],
          [1, 1, 1, 1],
          [1, 1, 1, 1]]],


        [[[2, 2, 2, 2],
          [2, 2, 2, 2],
          [2, 2, 2, 2],
          [2, 2, 2, 2]]],


        [[[3, 3, 3, 3],
          [3, 3, 3, 3],
          [3, 3, 3, 3],
          [3, 3, 3, 3]]]])

In [48]:
t[0]

tensor([[[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]]])

In [49]:
t[0][0]

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]])

In [50]:
t[0][0][0]

tensor([1, 1, 1, 1])

In [51]:
t[0][0][0][0]

tensor(1)

- flatten each image use PyTorch built-in function ``flatten``
- 或可以直接用``reshape``

In [52]:
t.flatten(start_dim = 1)

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

In [54]:
t.flatten(start_dim=1).shape

torch.Size([3, 16])

In [55]:
t.reshape(3,-1)

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

#### Element-Wise

- to implement element-wise operation, two tensors must have the same shape
- element-wise component-wise point-wise mean the same thing

In [57]:
import torch
import numpy as np

In [58]:
t1 = torch.tensor([
    [1,2],
    [3,4]
],dtype = torch.float32)

t2 = torch.tensor([
    [9,8],
    [7,6]
],dtype = torch.float32)

- addtion,substract,multiply,divide is an element-wise operation

In [59]:
t1 + t2

tensor([[10., 10.],
        [10., 10.]])

- notice that scalar can be used in element-wise operations 
- this concept is **tensor broadcasting**

In [64]:
np.broadcast_to(2,t1.shape) # broadcast

array([[2, 2],
       [2, 2]])

In [60]:
t1 + 2 # equals to t1.add(2)

tensor([[3., 4.],
        [5., 6.]])

In [61]:
t1 -2 # equals to  t1.sub(2)

tensor([[-1.,  0.],
        [ 1.,  2.]])

In [62]:
t1 * 2 # equals to t1.mul(2)

tensor([[2., 4.],
        [6., 8.]])

In [63]:
t1 / 2 # equals to t1.div(2)

tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])

- shape不同的tensor也可以进行运算,low rank通过broadcast升维

In [65]:
t1 = torch.tensor([
    [1,1],
    [1,1]
],dtype = torch.float32)

t2 = torch.tensor([2,4],dtype = torch.float32)

In [67]:
np.broadcast_to(t2.numpy(),t1.shape)

array([[2., 4.],
       [2., 4.]], dtype=float32)

In [69]:
t1 + t2

tensor([[3., 5.],
        [3., 5.]])

- **Comparison operations** are also element-wise

In [70]:
t = torch.tensor([
    [0,5,7],
    [6,0,7],
    [0,8,0]
],dtype = torch.float32)

In [71]:
t.eq(0) # eq 等于

tensor([[ True, False, False],
        [False,  True, False],
        [ True, False,  True]])

In [72]:
t.lt(0) # lt 小于

tensor([[False, False, False],
        [False, False, False],
        [False, False, False]])

In [73]:
t.le(0) # le 小于等于

tensor([[ True, False, False],
        [False,  True, False],
        [ True, False,  True]])

In [74]:
t.gt(0) #  gt 大于

tensor([[False,  True,  True],
        [ True, False,  True],
        [False,  True, False]])

In [75]:
t.ge(0) # ge 大于等于

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

- 上面均用到了**Broadcasting**

#### Redution

- 减少张量中数据的数量
- 求和操作是Redution操作
- 通常情况下是对特定的axis进行reduction操作

In [76]:
import torch
import numpy as np

In [77]:
t = torch.tensor([
    [0,1,0],
    [2,0,2],
    [0,3,0]
],dtype = torch.float32)

In [78]:
t.sum()

tensor(8.)

In [79]:
t = torch.tensor([
    [1,1,1,1],
    [2,2,2,2],
    [3,3,3,3]
],dtype = torch.float32)

In [80]:
t.sum(dim = 0)

tensor([6., 6., 6., 6.])

In [82]:
t[0] + t[1] + t[2]

tensor([6., 6., 6., 6.])

In [81]:
t.sum(dim = 1)

tensor([ 4.,  8., 12.])

In [83]:
t[0].sum()

tensor(4.)

In [84]:
t[1].sum()

tensor(8.)

In [85]:
t[2].sum()

tensor(12.)

In [92]:
torch.stack((t[0].sum(),t[1].sum(),t[2].sum()))

tensor([ 4.,  8., 12.])

##### Argmax

- 返回tensor中最大值的下标

In [93]:
t= torch.tensor([
    [1,0,0,2],
    [0,3,3,0],
    [4,0,0,5]
],dtype = torch.float32)

In [94]:
t.max()

tensor(5.)

In [95]:
t.argmax()

tensor(11)

In [96]:
t.flatten()

tensor([1., 0., 0., 2., 0., 3., 3., 0., 4., 0., 0., 5.])

In [97]:
t.max(dim = 0)

torch.return_types.max(
values=tensor([4., 3., 3., 5.]),
indices=tensor([2, 1, 1, 2]))

In [98]:
t.argmax(dim= 0)

tensor([2, 1, 1, 2])

In [99]:
t.max(dim =1 )

torch.return_types.max(
values=tensor([2., 3., 5.]),
indices=tensor([3, 2, 3]))

In [100]:
t.argmax(dim =1 )

tensor([3, 2, 3])

#### Access

- get tensor value as a number
- ``item()`` only works with scalar value tensor

In [101]:
t = torch.tensor([
    [1,2,3],
    [4,5,6],
    [7,8,9]
],dtype = torch.float32)

In [102]:
t.mean()

tensor(5.)

In [103]:
t.mean().item()

5.0

In [104]:
t.mean(dim = 0).tolist()

[4.0, 5.0, 6.0]

In [105]:
t.mean(dim = 0).numpy()

array([4., 5., 6.], dtype=float32)