In [7]:
with open('branch_data.txt','r') as branch_data:
    source,end,r,x,y,k = branch_data.readline().split()

In [9]:
1/(0.01+0.085j)

(1.36518771331058-11.60409556313993j)

In [11]:
a = [i for i in range(5)]
a

[0, 1, 2, 3, 4]

In [13]:
real = 0.01
imag = 0.085
com = complex(real,imag)
com
type(com)

complex

In [15]:
type(com.imag)

float

In [17]:
a  = [i for i in range(0,8,2)]
a

[0, 2, 4, 6]

In [19]:
import numpy as np 
mat = np.zeros((9,9),dtype=complex)

with open('branch_data.txt','r') as branch_data:
    source,end,r,x,y,k = branch_data.readline().split()
    source,end,r,x,y,k = int(source),int(end),float(r),float(x),float(y),float(k)
    resistance = complex(r,x)
    # 先计算互导纳
    mat[source-1][end-1],mat[end-1][source-1] = 1/(-resistance),1/(-resistance)
    mat[source-1][source-1] += (1/resistance+0.5*y)
    mat[end-1][end-1] += (1/resistance+0.5*y)

branch_data.close()
mat[0]

array([0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
       0.+0.j])

In [20]:
a = np.zeros((3,4))
a.shape

(3, 4)

In [21]:
a = np.array([5,4,3,2])
a[-1]

2

In [22]:
import cmath
import math
cmath.polar(complex(1,1))[1] * (180/math.pi)

45.0

In [23]:
np.zeros((8,1))

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [24]:
list((2,3))

[2, 3]

In [25]:
a = np.abs(np.array([-5,2]))
a

array([5, 2])

In [1]:
import numpy as np 
a = np.zeros(2,dtype=complex)
b = np.zeros(2,dtype=complex)
a[0],a[1] = complex(1,2),complex(3,4)
b[0],b[1] = complex(5,6),complex(7,8)

In [7]:
abs(a-b)

array([5.65685425, 5.65685425])

In [6]:
np.sqrt(np.sum(np.square([4,4])))

5.656854249492381